CONSUMER_KEY: fzwWCvA2hmY0KHT9w0gri7uOk
CONSUMER_SECRET: 1OSYEFCRzntG3Z1HCChGSMjMXCvoCg0DZmCp1IelJlhomiEt5j
ACCESS_TOKEN: 60920627-3y6s9KaQPS6cmCAur6Rnak0flUNh4FxRuDJC73y6p
ACCESS_TOKEN_SECRET: QY6Jfy945i4VHQMa5nDozXMRvI6ZvjGiBtHJZtpWY14Qz
CODEA_TAG_API_TOKEN: f823eda872175ce3daaf2c93bb4ecfb2